analyzer:
  errors:
    avoid_print: ignore
    unused_import: error
    unused_local_variable: warning

  exclude:
    - build/**
    - "**/*.g.dart"

linter:
  rules:
    - prefer_const_constructors
    - avoid_unused_constructor_parameters
