name: appdev
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  get: ^4.7.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^6.2.1
  sidebarx: ^0.17.2
  flutter_advanced_cards: ^1.0.0
  http: ^1.5.0
  connectivity_plus: ^6.0.3
  flutter_speed_dial: ^7.0.0
  awesome_dialog: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    

